name: 'sb-cute-action'
description: 'custom action by sb: sb-cute-action'
author: 'sb'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'blue'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'How many ms to wait'
    required: true
    default: '1000'
  sb_input:
    description: 'Does it even work?'
    required: true
    default: 'no'

# Define your outputs here.
outputs:
  time:
    description: 'the time'
  sb_ouptut:
    descriotion : 'sb_output'

runs:
  using: node20
  main: dist/index.js
